import { normalizeLocale } from "./i18n/locales.js";

const TIMEOUT_MS=1500;
function config(env={}){const url=String(env.SUPABASE_URL||"").trim().replace(/\/$/,"");const key=String(env.SUPABASE_SECRET_KEY||"").trim();return{url,key,urlOk:/^https:\/\//i.test(url),keyOk:key.startsWith("sb_secret_"),configured:/^https:\/\//i.test(url)&&key.startsWith("sb_secret_")};}
function telegramId(value){const raw=String(value??"").trim();return/^\d{1,20}$/.test(raw)?raw:null;}
async function request(env,path,options={}){const cfg=config(env);if(!cfg.configured)return{ok:false,reason:"not_configured"};const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),TIMEOUT_MS);try{const response=await fetch(`${cfg.url}/rest/v1/${path}`,{...options,signal:controller.signal,headers:{apikey:cfg.key,"Content-Type":"application/json",...(options.headers||{})}});if(!response.ok)return{ok:false,reason:`http_${response.status}`};return{ok:true,response};}catch{return{ok:false,reason:"request_failed"};}finally{clearTimeout(timer);}}
export async function readLocalePreference(userId,env){const id=telegramId(userId);if(!id)return null;const result=await request(env,`telegram_user_preferences?telegram_user_id=eq.${id}&select=locale&limit=1`,{method:"GET",headers:{Accept:"application/json"}});if(!result.ok)return null;try{const rows=await result.response.json();const locale=rows&&rows[0]&&rows[0].locale;return locale==="en"||locale==="sw"?locale:null;}catch{return null;}}
export async function writeLocalePreference(userId,locale,env){const id=telegramId(userId);if(!id)return false;const normalized=normalizeLocale(locale);const result=await request(env,"telegram_user_preferences?on_conflict=telegram_user_id",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify({telegram_user_id:id,locale:normalized,updated_at:new Date().toISOString()})});return result.ok;}
export function preferenceStorageConfigured(env){return config(env).configured;}
export function preferenceStorageStatus(env){const cfg=config(env);return{urlPresent:!!cfg.url,urlValid:cfg.urlOk,secretPresent:!!cfg.key,secretFormatValid:cfg.keyOk,configured:cfg.configured};}
