/**
 * Tool registry — single source of truth for UI cards and future routing.
 * status: "available" | "coming_soon"
 */

export const TOOL_CATEGORIES = [
  {
    id: "website-seo",
    name: "Website & SEO",
    description: "Analyze sites, crawlers, performance and search readiness.",
    tools: [
      {
        id: "seo-checker",
        name: "SEO Checker",
        description: "Inspect on-page SEO signals for a given URL.",
        route: "/tools/seo",
        status: "coming_soon",
      },
      {
        id: "http-status",
        name: "HTTP Status Checker",
        description: "Check response status codes and redirects.",
        route: "/tools/http-status",
        status: "coming_soon",
      },
      {
        id: "robots",
        name: "Robots.txt Analyzer",
        description: "Fetch and analyze robots.txt rules.",
        route: "/tools/robots",
        status: "coming_soon",
      },
      {
        id: "sitemap",
        name: "Sitemap Analyzer",
        description: "Inspect XML sitemaps and coverage.",
        route: "/tools/sitemap",
        status: "coming_soon",
      },
      {
        id: "mobile-friendly",
        name: "Mobile Friendly Checker",
        description: "Evaluate mobile usability signals.",
        route: "/tools/mobile",
        status: "coming_soon",
      },
      {
        id: "lighthouse",
        name: "Lighthouse / Performance",
        description: "Performance, accessibility and best-practice insights.",
        route: "/tools/performance",
        status: "coming_soon",
      },
    ],
  },
  {
    id: "dns-email",
    name: "DNS & Email",
    description: "Inspect DNS records and email authentication setup.",
    tools: [
      {
        id: "dns-lookup",
        name: "DNS Lookup",
        description: "Query common DNS record types for a domain.",
        route: "/tools/dns",
        status: "available",
      },
      {
        id: "mx",
        name: "MX Record Checker",
        description: "Check the mail exchange records configured for a domain.",
        route: "/tools/mx",
        status: "coming_soon",
      },
      {
        id: "spf",
        name: "SPF Checker",
        description: "Validate SPF records and policy.",
        route: "/tools/spf",
        status: "coming_soon",
      },
      {
        id: "dkim",
        name: "DKIM Checker",
        description: "Inspect DKIM selectors and keys.",
        route: "/tools/dkim",
        status: "coming_soon",
      },
      {
        id: "dmarc",
        name: "DMARC Checker",
        description: "Review DMARC policy and reporting setup.",
        route: "/tools/dmarc",
        status: "coming_soon",
      },
      {
        id: "nameserver",
        name: "Nameserver Lookup",
        description: "List authoritative nameservers for a domain.",
        route: "/tools/nameserver",
        status: "coming_soon",
      },
    ],
  },
  {
    id: "security",
    name: "Security",
    description: "Basic security posture and infrastructure detection.",
    tools: [
      {
        id: "blacklist",
        name: "Blacklist Checker",
        description: "Check domain/IP against common blacklists.",
        route: "/tools/blacklist",
        status: "coming_soon",
      },
      {
        id: "ssl",
        name: "SSL/TLS Checker",
        description: "Inspect certificate chain and TLS configuration.",
        route: "/tools/ssl",
        status: "coming_soon",
      },
      {
        id: "security-headers",
        name: "Security Headers",
        description: "Review HTTP security headers.",
        route: "/tools/security-headers",
        status: "coming_soon",
      },
      {
        id: "port-scanner",
        name: "Basic Port Scanner",
        description: "Check common open ports (carefully rate-limited).",
        route: "/tools/ports",
        status: "coming_soon",
      },
      {
        id: "waf",
        name: "WAF Detector",
        description: "Detect presence of a Web Application Firewall.",
        route: "/tools/waf",
        status: "coming_soon",
      },
      {
        id: "cloudflare",
        name: "Cloudflare Detector",
        description: "Detect Cloudflare proxying and related signals.",
        route: "/tools/cloudflare",
        status: "coming_soon",
      },
      {
        id: "cdn",
        name: "CDN Detector",
        description: "Identify CDN providers in use.",
        route: "/tools/cdn",
        status: "coming_soon",
      },
    ],
  },
  {
    id: "infrastructure",
    name: "Infrastructure",
    description: "Hosting, IP, ASN and server information.",
    tools: [
      {
        id: "ip",
        name: "IP Lookup",
        description: "Resolve and inspect IP address details.",
        route: "/tools/ip",
        status: "coming_soon",
      },
      {
        id: "asn",
        name: "ASN Lookup",
        description: "Find Autonomous System information.",
        route: "/tools/asn",
        status: "coming_soon",
      },
      {
        id: "hosting",
        name: "Hosting Provider Detector",
        description: "Identify likely hosting or cloud provider.",
        route: "/tools/hosting",
        status: "coming_soon",
      },
      {
        id: "rdns",
        name: "Reverse DNS",
        description: "Perform reverse DNS (PTR) lookups.",
        route: "/tools/rdns",
        status: "coming_soon",
      },
      {
        id: "http-headers",
        name: "HTTP Headers",
        description: "Fetch and display response headers.",
        route: "/tools/headers",
        status: "coming_soon",
      },
      {
        id: "server-info",
        name: "Server Information",
        description: "Gather basic server and technology signals.",
        route: "/tools/server",
        status: "coming_soon",
      },
    ],
  },
];
